feat: html-report flag
afdesk/scan2html pull request #51
Opened 2023-04-17 08:05 UTC by malikovmm

2023-04-18 10:15 UTC, afdesk requested changes

2023-04-18 10:15 UTC, afdesk commented on main.go
> +}
I'm not sure that it works correctly for all cases, because the order is important for your implementation.
let's just remove these custom flags from `os.Args`, and pass to Trivy a new slice

2023-04-18 10:15 UTC, afdesk commented on main.go
> +	trivyCommand := os.Args[1:trivyCommandBorder]
Go functions can return several values:
```sh
def getParams() (string, strign, []string) {}
```
or we can create a new struct:
```sh
type pluginFlags struct {
  htmlFile string
  inputFile string
}
// and return it
def getFlags() (*pluginFlags, []string) {
}
```
`[]string` - is new arguments for Trivy,

Wdyt?

2023-04-23 16:32 UTC, afdesk requested changes

2023-04-23 16:32 UTC, afdesk commented on main.go
> +
this block calls `slices.Index()` a lot, that contains `for` under the hood:
https://cs.opensource.google/go/x/exp/+/133eef43:slices/slices.go;l=106

we have to refactor it.

![изображение](https://user-images.githubusercontent.com/19297627/233851952-a76654bd-2d1d-4b8a-bc73-7e707e598ee9.png)

2023-04-23 17:19 UTC, afdesk commented on main.go
> +
i meant the first loop in `excludePluginFlags` and `getFlagValue` do the same things, just in two different places.
so I suggested to return several values from `excludePluginFlags`

2023-04-26 06:16 UTC, nikpivkin approved these changes

2023-04-26 06:25 UTC, afdesk approved these changes

2023-04-26 06:25 UTC, merged