feat: replace js render to template
afdesk/scan2html pull request #57
Opened 2024-11-27 09:51 UTC by olsova

2024-11-27 10:15 UTC, afdesk requested changes
some needed JS was removed, so the search doesn't work now

2024-11-27 10:15 UTC, afdesk commented on go.mod
>  go 1.19
let's bump the version up

2024-11-27 10:15 UTC, afdesk commented on go.mod
> +	github.com/aquasecurity/trivy v0.38.3
let's try to use the latest version

2024-12-02 06:18 UTC, afdesk requested changes
I left a few small comments
PTAL
thanks

2024-12-02 06:18 UTC, afdesk commented on main.go
> +	rootCmd, err := initFlags()
it seems `initFlags` isn't relevant, something like `initRootCmd` looks better, isn't it?

2024-12-02 06:18 UTC, afdesk commented on main.go
> +		log.Fatalf("%+v", err)
fatal log without description doesn't look great

2024-12-02 06:18 UTC, afdesk commented on main.go
> +		log.Fatalf("%+v", err)
ditto

2024-12-02 06:18 UTC, afdesk commented on main.go
> +		return err
maybe we should add some comment for this error too? It will be hard to look for a reason of unknown errors

2024-12-02 06:27 UTC, nikpivkin commented on render/template/html.tpl
> +    <link rel="stylesheet" href="index.css">
The link to the css file is no longer needed

2024-12-02 06:29 UTC, nikpivkin commented on render/render.go
> +	if err := json.NewDecoder(bytes.NewReader(inputData)).Decode(&output); err != nil {
The data already exists in memory, rather than coming from a stream, so you can use `json.Unmarshal`

2024-12-02 06:33 UTC, nikpivkin commented on render/render.go
> +	file, err := os.Create(fileName)
I think the output file should be named `output`

2024-12-02 06:34 UTC, nikpivkin commented on render/render_test.go
> +			log.Println(string(expected) == string(actual))
debug? :)

2024-12-02 06:36 UTC, nikpivkin commented on render/render_test.go
> +			assert.Equal(t, string(expected), string(actual))
You can compare the bytes

2024-12-02 09:38 UTC, DmitriyLewen commented on main.go
> -	availableFlags   = []string{"--html-result", "--load-result"}
We need to update `README.MD` (new flags, etc.)

2024-12-02 09:38 UTC, DmitriyLewen commented on render/template/html.tpl
not all fields are centering.
e.g.:
![изображение](https://github.com/user-attachments/assets/28083b87-9a2c-4a41-b43d-c5fe5dc23d71)

2024-12-02 09:38 UTC, DmitriyLewen commented on render/template/html.tpl
We need to think about secrets (perhaps in another PR).
![изображение](https://github.com/user-attachments/assets/653b7968-aaaa-47ad-a459-94e85ea0ad25)

2024-12-02 12:08 UTC, afdesk approved these changes

2024-12-02 16:59 UTC, nikpivkin approved these changes

2024-12-03 05:53 UTC, DmitriyLewen approved these changes

2024-12-03 06:01 UTC, merged